### ISSUE TITLE
WSManListener for HTTPS should support certificates using a DN as the subject

### ISSUE THREAD

**Issue by nabrond** [PlagueHO/WSManDsc#3]
The code for WSManListener assumes that the certificate's subject will only contain the CN of the server (e.g. CN=server.mydomain.local). Some organizations issue certificates with a DN as the subject (eg. CN=server.mydomain.local, O=Some Company, ST=Pennsylvania, C=US).

Can this resource be updated to support this scenario?

**Comment by PlagueHO** [comment]
Hi @nabrond - that is a really good point and suggestion. I'll get the change made.

What I can do is add a new parameter that allows you to specify the additional component of the DN that would be added to the hostname.

E.g.
```powershell
        WSManListener HTTPS
        {
            Transport = 'HTTPS'
            Ensure    = 'Present'
            Issuer    = 'CN=CONTOSO.COM Issuing CA, DC=CONTOSO, DC=COM'
            DN        = 'O=Some Company, ST=Pennsylvania, C=US'
} # End of WSManListener Resource
```
This would then look for a cert with the subject (when run on server.mydomain.local):
CN=server.mydomain.local, O=Some Company, ST=Pennsylvania, C=US

Does this sound like it would work for you?

**Comment by nabrond** [comment]
@PlagueHO took a look at my environment this morning and I think your proposed method will work for me.

**Comment by PlagueHO** [comment]
@nabrond - cool. Ok. I'll get this done this weekend for you. Will have it done by first thing next week.

Is it OK if I update only the new WSManDsc resource version rather than my older cWSMan? The new WSManDsc resource is undergoing final submission to the MSFT resource kit so it will be the only one supported going forward. I'll deprecate the older cWSMan resource once this has gone in.

**Comment by nabrond** [comment]
Thanks @PlagueHO! It makes sense to update the version that is being merged into the resource kit rather than a version that will be deprecated. I posted against this version since this is what the PowerShell gallery version linked to.

**Comment by PlagueHO** [comment]
@nabrond Working on this now.

**Comment by PlagueHO** [comment]
@nabrond - I've made the changes to the WSManDsc resource module, but they're currently only available in the [ReviewTarget branch](https://github.com/PlagueHO/WSManDsc/tree/reviewTarget).

This newer WSManDsc resource module won't get published to the PS Gallery until it has made it over to the MSFT DSC Resource kit. This shouldn't be much longer now.

So you're welcome to use this newer version by downloading it straight from this repo (from the ReviewTarget) branch, but be aware that when it is accepted into the resource kit the version number and other details may change. When MSFT do accept it, they'll make it available in the PS Gallery.

**Comment by PlagueHO** [comment]
This feature has been merged and released to the PSGallery.
