### ISSUE TITLE
Export Dsc resource WSManConfig

### ISSUE THREAD

**Issue by Outek** [PlagueHO/WSManDsc#47]
Hi @PlagueHO 

Should this line not include WSManConfig?
https://github.com/PlagueHO/WSManDsc/blob/dev/WSManDsc.psd1#L73

# DSC resources to export from this module
DscResourcesToExport = @('WSManListener','WSManServiceConfig')

# DSC resources to export from this module
DscResourcesToExport = @('WSManListener','WSManServiceConfig','WSManConfig')

**Comment by PlagueHO** [comment]
Thanks @Outek - I noticed this too (raised a PR even :grin:) - just needs a review. You could review it for me if you want? https://github.com/PlagueHO/WSManDsc/pull/46
