### ISSUE TITLE
WSManListener: target CertificateThumbprint and write

### ISSUE THREAD

**Issue by ttdgcp** [PlagueHO/WSManDsc#8]
**Details of the scenario you tried and the problem that is occurring:**

I am trying to use WSManListener to create an HTTPS listener with a certificate that only has "CN=devOps"; it is not issued by the local machine.  Is there any way to pass a thumbprint directly to the Find-Certificate cmdlet instead of having it search through issuers and DN and forcing the issuer to be the local computer hostname? I noticed the CertificateThumbprint parameter, but it is only configured for read operations and not write?

**The DSC configuration that is using the resource (as detailed as possible):**

I am primarily attempting to use this resource via Chef, but I have tested locally with DSC and have the same issue:

```
Configuration Example
{
    param
    (
        [Parameter()]
        [System.String[]]
        $NodeName = 'localhost'
    )
    Import-DscResource -Module WSManDsc
    Node $NodeName
    {
        WSManListener HTTPS
        {
            Transport = 'HTTPS'
            Ensure    = 'Present'
            Issuer    = 'CN=devOps'
        } # End of WSManListener Resource
    } # End of Node
} # End of Configuration
```

The relevant details of the certificate:
```
Issuer                   : CN=devOps
Subject                  : CN=devOps
```

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Server 2016, PowerShell 5.1

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
2.0.0.51

If you need any more details, please let me know; thanks for your excellent work on this module.

**Comment by PlagueHO** [comment]
Hi @ttdgcp - this does look like I can implement this fairly easily by adding a Thumbrpint parameter to Find-Certificate and to Set/Test-TargetResource.

So to confirm, you'd want to be able to do something like this:
```powershell
Configuration Example
{
    param
    (
        [Parameter()]
        [System.String[]]
        $NodeName = 'localhost'
    )
    Import-DscResource -Module WSManDsc
    Node $NodeName
    {
        WSManListener HTTPS
        {
            Transport = 'HTTPS'
            Ensure    = 'Present'
            Thumbprint    = 'D37F61D57CB0481F3D77EDAC7DE72196C4314E2C'
        } # End of WSManListener Resource
    } # End of Node
} # End of Configuration
```

Is that correct? If so, then I'll see if I can get it done over the holiday break (next week or so).

Thanks for you raising this too BTW! :grin:

**Comment by PlagueHO** [comment]
Tagging @poblahblahblah to confirm that the above proposal would address your requirements?

**Comment by ttdgcp** [comment]
@PlagueHO Sorry for the delay in getting back to you.

That's exactly correct- being able to specify via a thumbprint parameter would be excellent! Thanks for taking the time.

**Comment by PlagueHO** [comment]
No worries @ttdgcp ! I'll get onto it this weekend! Thanks for getting back to me :grin:

**Comment by PlagueHO** [comment]
@ttdgcp and @poblahblahblah , I've finished the changes now and you'll find them in the Dev branch. I'll release this to master (and the PS Gallery) in the next day.

**Comment by PlagueHO** [comment]
I've released the new version to PSGallery.

**Comment by ttdgcp** [comment]
@PlagueHO Sorry for the delay in testing this-- just getting back from vacation.

I've been testing with the latest version you've released, and am seeing the following error when using a certificate thumbprint:
`The WinRM client cannot process the request. The certificate CN and the hostname that were provided do not match.`

I am using the following configuration:
`Ensure                         = "Present"`
`Transport                     = "HTTPS"`
`CertificateThumbprint = "$thumbprinthere"`


I believe this is because I cannot specify (and write) the HostName parameter that the WinRM client demands. If we could add the hostname parameter to be able to write, I believe that would solve my use case.

Let me know what you think!

**Comment by PlagueHO** [comment]
Hi @ttdgcp . Ah I see. I think I can expose the host name and allow it to be overridden. I'll take a look tonight and see what I can determine.

Could you tell me what the CN in your certificate subject is (feel free to obfuscate any real DNS names)? This is so I can make a certificate to test with that is similar to yours. Also, are there any subject alternate names defined in the cert?

**Comment by ttdgcp** [comment]
@PlagueHO the CN is just "devOps", if that helps at all-- should be simple to test.

**Comment by PlagueHO** [comment]
Thanks @ttdgcp. Can you confirm you've been able to bind this certificate to a WSMan listener on a similar machine using a CN like this? Also, did your cert have any SAN (DNS names in it)? I've never tried a cert like this with a WSMan listener (usually I'm binding a cert issued to the hostname - so the DNS and Subject CN matches the machine).

Anyway, I'll try and jump into this tomorrow night (getting a bit late here now and I got side tracked with a new addition into xStorage).

**Comment by ttdgcp** [comment]
We're able to bind the certificate to a WSMan listener with the following command:
`New-WSManInstance winrm/config/Listener -SelectorSet @{ Address="*";Transport="HTTPS"} -ValueSet @{Hostname="devOps";CertificateThumbprint=$thumbprint}`

It's certainly a bit unorthodox, but it fits our use case.

Let me know if I can help any further- thank you for supporting this!

**Comment by PlagueHO** [comment]
@ttdgcp - I've moved this requirement over into a new issue #11. This is just so we can track it properly.
